apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  annotations: {}
  name: {{ .Release.Name }}-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
